version: '3.9'

services:
  game-mongo1:
    image: mongo:8.0
    container_name: game-mongo1
    ports:
      - "27018:27017"
    command: [ "mongod", "--replSet", "rs0" ]
    volumes:
      - game-mongodb-1:/data/db
    networks:
      - bb-network
  game-mongo2:
    image: mongo:8.0
    container_name: game-mongo2
    command: [ "mongod", "--replSet", "rs0" ]
    volumes:
      - game-mongodb-2:/data/db
    networks:
      - bb-network
  game-mongo3:
    image: mongo:8.0
    container_name: game-mongo3
    command: [ "mongod", "--replSet", "rs0" ]
    volumes:
      - game-mongodb-3:/data/db
    networks:
      - bb-network
  mongo-exporter:
    image: bitnami/mongodb-exporter:0.43.0
    container_name: mongo-exporter
    restart: always
    command:
      - "--mongodb.uri=mongodb://game-mongo3:27017"
      - "--discovering-mode"
      - "--collect-all"
    ports:
      - "9216:9216"
    depends_on:
      - game-mongo1
      - game-mongo2
      - game-mongo3
    networks:
      - bb-network
  game-service:
    build:
      context: ./../../..
      dockerfile: deploy/game/development/Dockerfile
      args:
        GO_IMAGE_NAME: golang
        GO_IMAGE_VERSION: 1.23
    container_name: game-service
    depends_on:
      - game-mongo1
      - game-mongo2
      - game-mongo3
    networks:
      - bb-network
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGO_URI=mongodb://game-mongo1:27017,game-mongo2:27017,game-mongo3:27017/bb-game?replicaSet=rs0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.game.rule=Host(`localhost`) && PathPrefix(`/game-service`)"
      - "traefik.http.middlewares.game-stripprefix.stripprefix.prefixes=/game-service"
      - "traefik.http.routers.game.middlewares=game-stripprefix,auth"
      - "traefik.http.services.game.loadbalancer.server.port=5003"
      - "traefik.http.middlewares.auth.forwardauth.address=http://auth-service:5000/api/v1/validate-token"
      - "traefik.http.middlewares.auth.forwardauth.authResponseHeaders=Authorization, X-User-Role, X-User-ID, X-Auth-Data"

networks:
  bb-network:
    external: true

volumes:
  game-mongodb-1:
  game-mongodb-2:
  game-mongodb-3:
