total_shutdown_timeout: 15s

http_server:
  port: 5003
  cors:
    allow_origins: "*"
  shutdown_context_timeout: "10s"

mongo:
  host: localhost
  port: 27018
  user: mongodb
  name: BB-game
  connect_timeout: 30s
  disconnect_timeout: 5s

broker:
  host: "kafka"
  port: "9092"

logger:
  file_path: "logs/game/service.log"
  use_local_time: true
  file_max_size_in_mb: 10
  file_max_age_in_days: 7