version: '3.9'

services:
  match-redis:
    image: bitnami/redis:6.2
    container_name: BB-match-redis
    restart: always
    ports:
      - '6381:6379'
    command: redis-server --loglevel warning --protected-mode no --save "" --appendonly no
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - user-redis:/data
    networks:
      - bb-network
  match-service:
    build:
      context: .
      args:
        GO_IMAGE_NAME: golang
        GO_IMAGE_VERSION: 1.23
    container_name: match-service
    depends_on:
      - match-redis
    networks:
      - bb-network
    environment:
      - KAFKA_BROKER=kafka:9092

networks:
  bb-network:
    external: true

volumes:
  user-redis: