name: Docker Image CI

on:
  push:
    paths:
      - "docker-compose.yml"
  pull_request:
    paths:
      - "docker-compose.yml"

jobs:

 build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract Docker image name and version from docker-compose.yml
      id: extract
      run: |
        IMAGE_NAME=$(grep 'image:' docker-compose.yml | cut -d' ' -f2)
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest .
        docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
    
