name: Build and Publish Docker Image

on:
  push:
    branches:
      - develop
    paths:
      - .github/workflows/docker-image.yml
  pull_request:
    branches:
      - develop

jobs:

 build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Get Secret
      run: echo "${{ secrets.GCR }}"
    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GCR }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: | 
          ghcr.io/nima-abdpoor/brain-blitz:latest