name: Build and Publish Docker Images

on:
  push:
    branches:
      - develop
    paths:
      - .github/workflows/docker-image.yml
      - deploy/**/development/Dockerfile
  pull_request:
    branches:
      - develop

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, match, game, user]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GCR }}

      - name: Debug File Paths
        run: pwd;ls -l deploy/${{ matrix.service }}/development/
      - name: Build and push Docker image for ${{ matrix.service }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deploy/${{ matrix.service }}/development/Dockerfile
          push: true
          tags: |
            ghcr.io/nima-abdpoor/brain-blitz/${{ matrix.service }}:latest
          build-args: |
            GO_IMAGE_NAME=golang
            GO_IMAGE_VERSION=1.23
